name: Android Debug artifact ondemand

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  apk:
    runs-on: ubuntu-20.04
    if: github.event.comment.body == 'Build test apk' && (github.actor == 'VishalNehra' || github.actor == 'TranceLove' || github.actor == 'EmmanuelMess' || github.actor == 'VishnuSanal')
    steps:
      - name: Github API Request
        id: request
        uses: octokit/request-action@v2.0.2
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ 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 }}
      - name: Get PR informations
        id: pr_data
        run: |
          echo "::set-output name=repo_name::${{ fromJson(steps.request.outputs.data).head.repo.full_name }}"
          echo "::set-output name=repo_clone_url::${{ fromJson(steps.request.outputs.data).head.repo.clone_url }}"
          echo "::set-output name=repo_ssh_url::${{ fromJson(steps.request.outputs.data).head.repo.ssh_url }}"
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          token: ${{ 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 }}
          repository: ${{fromJson(steps.request.outputs.data).head.repo.full_name}}
          ref: ${{fromJson(steps.request.outputs.data).head.ref}}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug --stacktrace
      - name: Upload fdroid artifact
        uses: actions/upload-artifact@v3
        with:
          name: Amaze-Fdroid-debug
          path: app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk
      - name: Upload play artifact
        uses: actions/upload-artifact@v3
        with:
          name: Amaze-Play-debug
          path: app/build/outputs/apk/play/debug/app-play-debug.apk
